### ISSUE TITLE
Possible typo error

### ISSUE THREAD

**Issue by nobeljacob** [beyondguo/label_confusion_learning#17]
In the code for lstm.py (https://github.com/beyondguo/label_confusion_learning/blob/master/models/lstm.py) in line 133, there is a possible typo as the variable name is "pred_porbs". however, in line 137, the variable "pred_probs" is used for calculating the loss. The variable "pred_probs" is not passed to the function and might be incorrectly accessed from line 152.

**Comment by beyondguo** [comment]
Thanks, you are right. I will fix it later.
