### ISSUE TITLE
LCM是如何参与训练的？

### ISSUE THREAD

**Issue by nicoyang-21** [beyondguo/label_confusion_learning#18]
LCM的损失如何定义的，谢谢了。

**Comment by beyondguo** [comment]
Could you please be more specific?

The loss of LCM is in the code (https://github.com/beyondguo/label_confusion_learning/blob/89a4eebfd5d947ea5ff1e87854209a43c7b8fde5/models/bert.py#L132), the description is also clearly put in the paper.

what's your problem?

**Comment by nicoyang-21** [comment]
Ok, I got it, thanks.
