### ISSUE TITLE
代码和论文不一致

### ISSUE THREAD

**Issue by outcast96** [beyondguo/label_confusion_learning#3]
代码中损失函数用的是交叉熵, 论文中怎么写的是kl散度

**Comment by beyondguo** [comment]
lcm_loss这个里面使用的就是kl散度，是由两个cross entropy拼起来的，是kl散度的因式分解

**Comment by outcast96** [comment]
> lcm_loss这个里面使用的就是kl散度，是由两个cross entropy拼起来的，是kl散度的因式分解

厉害
