### ISSUE TITLE
大佬，求给码云也上传个，GitHub代码拉不下来，||-_-

### ISSUE THREAD

**Issue by aiainui** [beyondguo/label_confusion_learning#4]

**Comment by beyondguo** [comment]
建议装一个Chrome ghelper，kexueshangwang

**Comment by aiainui** [comment]
> 建议装一个Chrome ghelper，kexueshangwang
嗯嗯，我分开下载搞定了，里面的datasets下载比较慢。
还有，大佬，来个requirements.txt吧？:P

**Comment by beyondguo** [comment]
基本上把TensorFlow， keras， bert4keras三个包的版本对上就不会出问题吧。readme里面给了版本。

matplotlib==3.1.3
numpy==1.18.1
gensim==3.8.1
tensorflow==1.15.0
jieba==0.42.1
pandas==1.0.1
bert4keras==0.8.4
Keras==2.3.1
scikit_learn==0.24.1

**Comment by aiainui** [comment]
> 基本上把TensorFlow， keras， bert4keras三个包的版本对上就不会出问题吧。readme里面给了版本。
> 
> matplotlib==3.1.3
> numpy==1.18.1
> gensim==3.8.1
> tensorflow==1.15.0
> jieba==0.42.1
> pandas==1.0.1
> bert4keras==0.8.4
> Keras==2.3.1
> scikit_learn==0.24.1

THX!!
