### ISSUE TITLE
loss1 = -K.categorical_crossentropy(simulated_y_true,simulated_y_true)

### ISSUE THREAD

**Issue by chenwanyuan** [beyondguo/label_confusion_learning#5]
loss1 = -K.categorical_crossentropy(simulated_y_true,simulated_y_true)
 are you sure?

**Comment by DeepTecher** [comment]
另，想请教一下：使用KL散度来计算loss。KL是在哪使用起来了。感谢。

**Comment by DeepTecher** [comment]
Can u help me explain it?

**Comment by beyondguo** [comment]
KL(p,q) = -CE(p,p)+CE(p,q)
