### ISSUE TITLE
loss1 calculation question

### ISSUE THREAD

**Issue by lni600** [beyondguo/label_confusion_learning#7]
anything wrong here?https://github.com/beyondguo/label_confusion_learning/blob/da019ec43f221b5157e77004081bb6f2dc9e2143/models/bert.py#L140

loss1 = -K.categorical_crossentropy(simulated_y_true,simulated_y_true)

Why the 2 parameters are both "simulated_y_true"?

**Comment by beyondguo** [comment]
KL(p,q) = -CE(p,p)+CE(p,q)
